# Generated by Django 5.2.17 on 2026-10-05 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scenario', models.TextField()),
                ('phase', models.CharField(choices=[('setup', 'Setup'), ('investigation', 'Investigation'), ('voting', 'Voting'), ('elimination', 'Elimination'), ('result', 'Result')], default='setup')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_human', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('gaddar', 'Gaddar'), ('patner', 'Patner')], max_length=20, null=True)),
                ('personality', models.CharField(blank=True, default='', max_length=400)),
                ('private_information', models.TextField(blank=True, default='')),
                ('is_alive', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
