# Generated by Django 5.2.17 on 2026-10-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scenario',
            field=models.TextField(blank=True, default=''),
        ),
    ]
