# Generated by Django 5.2.17 on 2026-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alibi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='scenario',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
