# Generated by Django 5.2.17 on 2026-10-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_alibi_alter_game_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='game.game')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='game.player')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='game.player')),
            ],
            options={
                'indexes': [models.Index(fields=['voter', 'target'], name='game_voting_voter_i_058323_idx'), models.Index(fields=['voter'], name='game_voting_voter_i_e7c81b_idx'), models.Index(fields=['target'], name='game_voting_target__51671b_idx')],
            },
        ),
    ]
