# Generated by Django 5.2.17 on 2026-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_voting'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voting',
            constraint=models.UniqueConstraint(fields=('voter', 'game'), name='one vote per game'),
        ),
        migrations.AddConstraint(
            model_name='voting',
            constraint=models.CheckConstraint(condition=models.Q(('voter', models.F('target')), _negated=True), name='voter_cannot_vote_themselves'),
        ),
    ]
