# Generated by Django 5.2.17 on 2026-10-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_player_alibi_alter_game_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='game.game')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recevier', to='game.player')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='game.player')),
            ],
            options={
                'indexes': [models.Index(fields=['sender', 'receiver'], name='conversatio_sender__37972c_idx'), models.Index(fields=['game'], name='game')],
            },
        ),
    ]
