# Generated by Django 5.2.17 on 2026-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
